[global]
    workgroup = WORKGROUP
    server role = standalone server
    map to guest = never
    security = user
    passdb backend = tdbsam
    smb ports = 445
    disable netbios = yes
    server min protocol = SMB2
    log level = 1
    load printers = no

[share]
    path = /srv/share
    read only = no
    browseable = yes
    valid users = smbr
    force user = smbr
    create mask = 0666
    directory mask = 0777
