// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// smbr_connect_cpp
void smbr_connect_cpp(std::string username, std::string password, std::string workgroup, int debug);
RcppExport SEXP _smbr_smbr_connect_cpp(SEXP usernameSEXP, SEXP passwordSEXP, SEXP workgroupSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type username(usernameSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type workgroup(workgroupSEXP);
    Rcpp::traits::input_parameter< int >::type debug(debugSEXP);
    smbr_connect_cpp(username, password, workgroup, debug);
    return R_NilValue;
END_RCPP
}
// smbr_disconnect_cpp
void smbr_disconnect_cpp();
RcppExport SEXP _smbr_smbr_disconnect_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    smbr_disconnect_cpp();
    return R_NilValue;
END_RCPP
}
// smbr_dir_cpp
DataFrame smbr_dir_cpp(std::string url);
RcppExport SEXP _smbr_smbr_dir_cpp(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(smbr_dir_cpp(url));
    return rcpp_result_gen;
END_RCPP
}
// smbr_stat_cpp
List smbr_stat_cpp(std::string url);
RcppExport SEXP _smbr_smbr_stat_cpp(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(smbr_stat_cpp(url));
    return rcpp_result_gen;
END_RCPP
}
// smbr_exists_cpp
bool smbr_exists_cpp(std::string url);
RcppExport SEXP _smbr_smbr_exists_cpp(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(smbr_exists_cpp(url));
    return rcpp_result_gen;
END_RCPP
}
// smbr_read_cpp
RawVector smbr_read_cpp(std::string url);
RcppExport SEXP _smbr_smbr_read_cpp(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(smbr_read_cpp(url));
    return rcpp_result_gen;
END_RCPP
}
// smbr_write_cpp
void smbr_write_cpp(std::string url, RawVector data, std::string mode);
RcppExport SEXP _smbr_smbr_write_cpp(SEXP urlSEXP, SEXP dataSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< RawVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    smbr_write_cpp(url, data, mode);
    return R_NilValue;
END_RCPP
}
// smbr_mkdir_cpp
void smbr_mkdir_cpp(std::string url, int mode);
RcppExport SEXP _smbr_smbr_mkdir_cpp(SEXP urlSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    smbr_mkdir_cpp(url, mode);
    return R_NilValue;
END_RCPP
}
// smbr_delete_cpp
void smbr_delete_cpp(std::string url);
RcppExport SEXP _smbr_smbr_delete_cpp(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    smbr_delete_cpp(url);
    return R_NilValue;
END_RCPP
}
// smbr_rename_cpp
void smbr_rename_cpp(std::string from, std::string to);
RcppExport SEXP _smbr_smbr_rename_cpp(SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type from(fromSEXP);
    Rcpp::traits::input_parameter< std::string >::type to(toSEXP);
    smbr_rename_cpp(from, to);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_smbr_smbr_connect_cpp", (DL_FUNC) &_smbr_smbr_connect_cpp, 4},
    {"_smbr_smbr_disconnect_cpp", (DL_FUNC) &_smbr_smbr_disconnect_cpp, 0},
    {"_smbr_smbr_dir_cpp", (DL_FUNC) &_smbr_smbr_dir_cpp, 1},
    {"_smbr_smbr_stat_cpp", (DL_FUNC) &_smbr_smbr_stat_cpp, 1},
    {"_smbr_smbr_exists_cpp", (DL_FUNC) &_smbr_smbr_exists_cpp, 1},
    {"_smbr_smbr_read_cpp", (DL_FUNC) &_smbr_smbr_read_cpp, 1},
    {"_smbr_smbr_write_cpp", (DL_FUNC) &_smbr_smbr_write_cpp, 3},
    {"_smbr_smbr_mkdir_cpp", (DL_FUNC) &_smbr_smbr_mkdir_cpp, 2},
    {"_smbr_smbr_delete_cpp", (DL_FUNC) &_smbr_smbr_delete_cpp, 1},
    {"_smbr_smbr_rename_cpp", (DL_FUNC) &_smbr_smbr_rename_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_smbr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
