# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smbr_connect_cpp <- function(username, password, workgroup = "", debug = 0L) {
    invisible(.Call(`_smbr_smbr_connect_cpp`, username, password, workgroup, debug))
}

smbr_disconnect_cpp <- function() {
    invisible(.Call(`_smbr_smbr_disconnect_cpp`))
}

smbr_dir_cpp <- function(url) {
    .Call(`_smbr_smbr_dir_cpp`, url)
}

smbr_stat_cpp <- function(url) {
    .Call(`_smbr_smbr_stat_cpp`, url)
}

smbr_exists_cpp <- function(url) {
    .Call(`_smbr_smbr_exists_cpp`, url)
}

smbr_read_cpp <- function(url) {
    .Call(`_smbr_smbr_read_cpp`, url)
}

smbr_write_cpp <- function(url, data, mode = "wb") {
    invisible(.Call(`_smbr_smbr_write_cpp`, url, data, mode))
}

smbr_mkdir_cpp <- function(url, mode = 0777L) {
    invisible(.Call(`_smbr_smbr_mkdir_cpp`, url, mode))
}

smbr_delete_cpp <- function(url) {
    invisible(.Call(`_smbr_smbr_delete_cpp`, url))
}

smbr_rename_cpp <- function(from, to) {
    invisible(.Call(`_smbr_smbr_rename_cpp`, from, to))
}

